server:
  port: 9103
spring:
  application:
    name: visits-sidecar
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: localhost:8761
sidecar:
  port: 9101
  health-uri: http://localhost:${sidecar.port}/health