server:
  port: 9100
spring:
  application:
    name: vets-sidecar
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: localhost:8761
sidecar:
  port: 9102
  health-uri: http://localhost:${sidecar.port}/health